package compilador;

public enum Dicionario {
	
	TIPO_INT_TOKEN(1),
	TIPO_FLOAT_TOKEN(2),
	TIPO_CHAR_TOKEN(3),
	
	IDENTIFICADOR_TOKEN(4),
	
	
	PR_WHILE_TOKEN(5),
	PR_IF_TOKEN(6),
	PR_FOR_TOKEN(7),
	PR_ELSE_TOKEN(8),
	PR_MAIN_TOKEN(9),
	PR_DO_TOKEN(10),
	PR_INT_TOKEN(11),
	PR_FLOAT_TOKEN(12),
	PR_CHAR_TOKEN(13),
	
	ABRE_PARENTESE_TOKEN(14),
	FECHA_PARENTESE_TOKEN(15),
	ABRE_CHAVE_TOKEN(16),
	FECHA_CHAVE_TOKEN(17),
	VIRGULA_TOKEN(18),
	PONTO_E_VIRGULA_TOKEN(19),
	
	OP_ARITMETICO_ADICAO_TOKEN(20),
	OP_ARITMETICO_SUBTRACAO_TOKEN(21),
	OP_ARITMETICO_MULTIPLICACAO_TOKEN(22),
	OP_ARITMETICO_DIVISAO_TOKEN(23),
	OP_ARITMETICO_IGUAL_TOKEN(24),
	
	OP_RELACIONAL_MAIOR_TOKEN(25),
	OP_RELACIONAL_MENOR_TOKEN(26),
	OP_RELACIONAL_MAIOR_IGUAL_TOKEN(27),
	OP_RELACIONAL_MENOR_IGUAL_TOKEN(28),
	OP_RELACIONAL_DIFERENTE_TOKEN(29),
	
	FIM_DE_ARQUIVO_TOKEN(30),
	ERRO(31);
	
	private int id;
	
	Dicionario(int id) {
		this.id = id;
	}
	
	public int getId() {
		return id;
	}
	
	
}
